version: '3.1'

services:

  wordpress_phone:
    image: wordpress
    restart: always
    container_name: beltelPhone
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db_phone
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

    volumes:
      - wordpress-phone:/var/www/html
      - ./child-themes/:/var/www/html/wp-content/themes/child-themes/
    depends_on:
        - db_phone
    networks:
      - project_phone
  db_phone:
    image: mysql:5.7
    container_name: mysql_phone
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-phone:/var/lib/mysql
    networks:
      - project_phone

networks:
  project_phone:
    driver: bridge

volumes:
  wordpress-phone:
  db-phone:
